### ISSUE TITLE
Getting NullPointerException using CassandraAdminOperations

### ISSUE THREAD

**Issue by harvi9s** [eugenp/tutorials#745] opened 2016-10-12 15:25 UTC
Can anyone help me resolve why CassandraAdminOperations is returning NullPointerException?

import org.springframework.data.cassandra.core.CassandraAdminOperations;

@Autowired
    private static CassandraAdminOperations adminTemplate;

@Before
    public void createTable() {
        adminTemplate.createTable(true, CqlIdentifier.cqlId(Test.TABLE_NAME),Test.class, new HashMap<String, Object>());
       }

**Comment by eugenp** [comment] 2017-12-27 15:49
Hey @harvi9s - sorry for the late reply here. I'm not able to reproduce the problem here, so I assume it's been fixed in the meantime. 
Closing (but feel free to reopen it if you need to). 
Cheers, 
Eugen.

**Closed by eugenp** 2017-12-27 15:49 UTC
