### ISSUE TITLE
SQLite example needs upgrade to work with spring framework 6

### ISSUE THREAD

**Issue by rameshputalapattu** [eugenp/tutorials#13235] opened 2023-01-03 11:56 UTC
The current SQLite example does not work with Spring framework 6. Can you please update the SQLite example to use the latest spring data JPA? Thanks in advance.

**Comment by ulisseslima** [comment] 2023-01-18 10:39
Hey, @rameshputalapattu.

We have an internal task to update articles to Spring 6, but it might take some time.

This issue will be kept open until then.

Cheers.

**Comment by gfmoore** [comment] 2023-01-25 18:23
Yes I need this too.
It seems SQLDialect is deprecated and registerColumnType is no longer recognised. I have no idea on what to do to get connected to the sqlite database. :(

**Comment by ulisseslima** [comment] 2023-01-25 19:24
@gfmoore you can use the [source code](https://github.com/eugenp/tutorials/tree/master/persistence-modules/spring-data-rest) from this article: https://www.baeldung.com/spring-boot-sqlite, which uses Spring 5.

In the meantime, StackOverflow can also help with upgrading to Spring 6.

**Comment by gfmoore** [comment] 2023-01-25 20:28
Thanks, I'm just trying it out now.

**Comment by gfmoore** [comment] 2023-01-25 20:59
Yay got it to work once I looked at my SQLDialect and not the authors - doh.

So what changed between v5 and v6 that causes it to fail. Obviously moving to Jakarta rather than javax, but that's fairly trivial.

It seems that the problem is in the SQLDialect ad that Dialect has been changed. I know that registerColumnType doesn't exist now, so ... or is it more involved than that?

**Comment by gilenodm** [comment] 2023-02-10 13:21
Hi guys.

I found the proper dialect for spring 6 and springboot 3. It will need some tweaking but it works.
In the same repository there are some more files (SQLiteIdentityColumnSupport, SQLiteSqlAstTranslator, AlterTableUniqueDelegate) that will also be needed.
Follow the link: https://github.com/hibernate/hibernate-orm/blob/main/hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SQLiteDialect.java

**Comment by kasramp** [comment] 2023-11-29 21:45
Hello,

The code of SQLite Dialog is updated to work with Spring 6 and Spring Boot 3. Additionally,[ the article](https://www.baeldung.com/spring-boot-sqlite) is updated.

**Closed by kasramp** 2023-11-29 21:45 UTC
Labels: triaged, on-jira

**Comment by gfmoore** [comment] 2023-11-29 21:50
Great, thanks.
