### ISSUE TITLE
spring-social-login - Unable to execute the code

### ISSUE THREAD

**Issue by JavaHelper** [eugenp/tutorials#2059] opened 2017-06-12 17:29 UTC
I am trying to run your code "spring-social-login", but I am getting some errors while running you code. I am facing errors mentioned in the below two links.

Request you to help to solve this issues. Looking for your earliest possible response.

https://stackoverflow.com/questions/44505276/app-domains-must-match-the-domain-of-the-facebook-web-games-url-https-mobile

https://stackoverflow.com/questions/44477717/url-blocked-this-redirect-failed-because-the-redirect-uri-is-not-white-listed-i

**Comment by eugenp** [comment] 2017-06-30 14:13
Hey @asif-anwar - if you have time, can you please have a look at this one - you'll probably get to it before I do. 
Cheers, 
Eugen.

**Comment by asif-anwar** [comment] 2017-07-01 10:58
@eugenp 
I will look into this day after tomorrow.
Thanks
Asif

**Comment by asif-anwar** [comment] 2017-07-03 19:36
Hi @JavaHelper,

Could you please try following steps and update me,

1. Add new app at _https://developers.facebook.com_
2. In Settings-->Basic, add platform as "Website" and  Site URL as _http://localhost:8080/_
3. Add "Facebook Login" product  from PRODUCTS section 
4. In product settings, update _Valid OAuth redirect URIs_ as _http://localhost:8080_
5. Run the application and hit "Login using Facebook" button

Thanks
Asif

**Comment by eugenp** [comment] 2017-07-29 16:53
Hey @JavaHelper  - not sure if you got the last comment here. I'm closing this issue, but feel free to re-open it if the problem is still there. 

Cheers, 
Eugen.

**Closed by eugenp** 2017-07-29 16:53 UTC
