### ISSUE TITLE
Client crashes on 32293 th request. 

### ISSUE THREAD

**Issue by mitendraanand** [eugenp/tutorials#2925] opened 2017-10-31 08:41 UTC
Response received from server:
greeting: "Hello, Mitendra Anand"
 Request Count: 32293
Exception in thread "main" io.grpc.StatusRuntimeException: UNAVAILABLE
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:210)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:191)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:124)
        at com.citadel.grpc.HelloServiceGrpc$HelloServiceBlockingStub.hello(HelloServiceGrpc.java:138)
        at com.citadel.grpc.client.GrpcClient.main(GrpcClient.java:24)
Caused by: io.netty.channel.AbstractChannel$AnnotatedSocketException: Cannot assign requested address: ld-dbn-boclr008/10.31.151.12:2020
        at sun.nio.ch.Net.connect0(Native Method)
        at sun.nio.ch.Net.connect(Net.java:454)
        at sun.nio.ch.Net.connect(Net.java:446)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
        at io.netty.util.internal.SocketUtils$3.run(SocketUtils.java:83)
        at io.netty.util.internal.SocketUtils$3.run(SocketUtils.java:80)
        at java.security.AccessController.doPrivileged(Native Method)
        at io.netty.util.internal.SocketUtils.connect(SocketUtils.java:80)
        at io.netty.channel.socket.nio.NioSocketChannel.doConnect(NioSocketChannel.java:308)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.connect(AbstractNioChannel.java:254)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1291)
        at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:545)
        at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:530)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.connect(Http2ConnectionHandler.java:454)
        at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:545)
        at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:530)
        at io.netty.channel.ChannelDuplexHandler.connect(ChannelDuplexHandler.java:50)
        at io.grpc.netty.ProtocolNegotiators$AbstractBufferingHandler.connect(ProtocolNegotiators.java:458)
        at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:545)
        at io.netty.channel.AbstractChannelHandlerContext.access$1000(AbstractChannelHandlerContext.java:38)
        at io.netty.channel.AbstractChannelHandlerContext$11.run(AbstractChannelHandlerContext.java:535)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.BindException: Cannot assign requested address
        ... 27 more

**Client Code**

    public static void main(String[] args) throws InterruptedException {
        Timer t = new Timer();
        t.start();

        for (int i = 0; i < 30000000; ++i) {
            ManagedChannel channel = ManagedChannelBuilder.forAddress("localhost", 2020)
                .usePlaintext(true)
                .build();

            HelloServiceGrpc.HelloServiceBlockingStub stub 
            = HelloServiceGrpc.newBlockingStub(channel);

            HelloResponse helloResponse = stub.hello(HelloRequest.newBuilder()
                .setFirstName("Mitendra")
                .setLastName("Anand")
                .build());

            System.out.println("Response received from server:\n" + helloResponse + " Request Count: " + i);

            channel.shutdown();
        }

        t.stop();

        System.out.println("Elaapsed Time: " +  t.getDuration() / 1000000 + " ms.");        
    }

**Comment by pivovarit** [comment] 2017-11-04 09:14
The problem is that you're opening and closing the channel 30000000 times! Which is killing the server. If you move the "handshake" outside the loop, you can see that everything speeds up a lot and simply keeps going. 

I can't promise if it works until the 30000000th time, though ;) I waited only till 500_000th request.

**Closed by pivovarit** 2017-11-04 09:14 UTC
