### ISSUE TITLE
Build failure in Autovalue module

### ISSUE THREAD

**Issue by saravanan-kandaswamy** [eugenp/tutorials#6800] opened 2019-04-23 03:04 UTC
autovalue module compilation errors.

[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ autovalue ---                                                                                             
[INFO] Changes detected - recompiling the module!                                                                                                                            
[INFO] Compiling 16 source files to D:\Works\JEE\eugenp\tutorials\autovalue\target\classes                                                                                   
[INFO] -------------------------------------------------------------                                                                                                         
[ERROR] COMPILATION ERROR :                                                                                                                                                  
[INFO] -------------------------------------------------------------                                                                                                         
[ERROR] /D:/Works/eugenp/tutorials/autovalue/src/main/java/com/baeldung/autofactory/provided/IntermediateAssembler.java:[5,20] package javafx.scene does not exist       
[ERROR] /D:/Works/eugenp/tutorials/autovalue/src/main/java/com/baeldung/autofactory/provided/IntermediateAssembler.java:[15,28] cannot find symbol                       
  symbol:   class Camera                                                                                                                                                     
  location: class com.baeldung.autofactory.provided.IntermediateAssembler                                                                                                    
[ERROR] /D:/Works/eugenp/tutorials/autovalue/src/main/java/com/baeldung/autofactory/provided/IntermediateAssembler.java:[18,53] cannot find symbol                       
  symbol:   class Camera                                                                                                                                                     
  location: class com.baeldung.autofactory.provided.IntermediateAssembler                                                                                                    
[ERROR] /D:/Works/eugenp/tutorials/autovalue/target/generated-sources/annotations/com/baeldung/autofactory/provided/IntermediateAssemblerFactory.java:[12,26] cannot find
 symbol                                                                                                                                                                      
  symbol:   class Camera                                                                                                                                                     
  location: class com.baeldung.autofactory.provided.IntermediateAssemblerFactory                                                                                             
[ERROR] /D:/Works/eugenp/tutorials/autovalue/target/generated-sources/annotations/com/baeldung/autofactory/provided/IntermediateAssemblerFactory.java:[15,48] cannot find
 symbol                                                                                                                                                                      
  symbol:   class Camera                                                                                                                                                     
  location: class com.baeldung.autofactory.provided.IntermediateAssemblerFactory                                                                                             
[INFO] 5 errors

**Comment by eric-martin** [comment] 2019-04-24 02:33
@saravanan-kandaswamy I'm not able to reproduce your problem. I'm able to build the module locally and our Jenkins instance is also able to build the module. 

Can you make sure you are running the latest master branch without any changes.

**Comment by saravanan-kandaswamy** [comment] 2019-04-25 11:20
Hi,

I am using Open JDK from Redhat for windows. 
openjdk version "1.8.0_201-2-redhat"
OpenJDK Runtime Environment (build 1.8.0_201-2-redhat-b09)
OpenJDK 64-Bit Server VM (build 25.201-b09, mixed mode)

With that its failing, however if i try to use Oracle JDK 8 the build is successful. 

Haven't said that there is an issue in the code. The import in IntermediateAssembler.java is wrong 
instead of importing the model Camera its importing the javax.scene.Camera which is not correct, which needs to be corrected. I have raised the pull request as well #6801 

I can change the bug description if needed.

**Comment by eric-martin** [comment] 2019-04-25 17:49
Nice catch @saravanan-kandaswamy! Thanks for the PR, it has been merged.

**Closed by eric-martin** 2019-04-25 17:49 UTC
Labels: in progress
