### ISSUE TITLE
Unknown host exception: 

### ISSUE THREAD

**Issue by Gurminder08** [eugenp/tutorials#7370] opened 2019-07-21 04:35 UTC
Tutorial : https://www.baeldung.com/spring-boot-minikube

I was trying to work out the tutorial provided in the link above, but it throws the following UnknownHostException:

I/O error on GET request for "http://demo-backend:8080": demo-backend; nested exception is java.net.UnknownHostException: demo-backend

Any help will be appreciated.

**Comment by eric-martin** [comment] 2019-07-21 15:42
@Gurminder08: You won't be able to access the web server using http://demo-backend. Take a look at the article again - you will need to use the IP address.

**Comment by Gurminder08** [comment] 2019-07-21 15:52
Hi, thanks for the reply, I did exactly that but it doesn't work. 

If you look at the code of demo-frontend from the following link: 

[KubernetestFrontEndApplication](https://github.com/eugenp/tutorials/blob/master/spring-cloud/spring-cloud-kubernetes/demo-frontend/src/main/java/com/baeldung/spring/cloud/kubernetes/frontend/KubernetesFrontendApplication.java)

It makes a Rest api call to demo-backend application using the RestTemplate. This is exactly where it throws the UnknownHostException.

**Comment by eric-martin** [comment] 2019-07-25 02:42
Ok. We will investigate.

**Comment by eric-martin** [comment] 2019-07-26 21:28
@Gurminder08 I have logged an internal ticket for investigation. I will update this issue as we make progress.

**Comment by maibin** [comment] 2019-12-17 22:15
@Gurminder08 - we did follow all the steps from the tutorial, checked everything and we cannot reproduce your error - everything works as intended on our side. You might have some ports blocked or changes to your localhost configuration.
Since we can't reproduce it, I am closing this one.

**Closed by maibin** 2019-12-17 22:15 UTC
Labels: in progress
