### ISSUE TITLE
Intermittent: java.net.SocketException: Unexpected end of file from server

### ISSUE THREAD

**Issue by tvdinh** [eugenp/tutorials#5838] opened 2018-12-04 05:11 UTC
Hi,

In this tutorial

[https://www.baeldung.com/docker-test-containers](url), or more specific 

```
https://github.com/eugenp/tutorials/blob/master/testing-modules/test-containers/src/test/java/com/baeldung/testconainers/GenericContainerLiveTest.java
```

I got this error intermittently:

```
java.net.SocketException: Unexpected end of file from server
```

Seems like the container is shutdown before the request has been served completely. Is there away to avoid this ? Add buffer time between test finish time and the time the container is shutdown and removed ?

Thanks,
Tuan

**Comment by eric-martin** [comment] 2018-12-09 15:18
@tvdinh We have an internal ticket logged about this issue. I will keep this ticket updated with our progress.

**Comment by tvdinh** [comment] 2018-12-20 03:20
@eric-martin: Any progress on this ?

**Comment by eric-martin** [comment] 2018-12-20 05:44
No progress yet. The ticket is still in our queue.

**Comment by eugenp** [comment] 2019-07-19 03:48
Jumping in here with an update, as it's been quite a while. 
Unfortunately, we can't reproduce it (the team tried to do that on several platforms). So, it either got fixed in the meantime, which is the one advantage of being late :) - or it wasn't there. 
Hope that helps, @tvdinh 

Closing this one. 
Cheers, 
Eugen.

**Closed by eugenp** 2019-07-19 03:48 UTC
Labels: in progress
