### ISSUE TITLE
There is no variable ENTITY_MANAGER in org.springframework.orm.jpa.EntityManagerHolder 

### ISSUE THREAD

**Issue by ameya** [eugenp/tutorials#11866] opened 2022-02-26 04:28 UTC
Hi was working on https://www.baeldung.com/java-bootstrap-jpa jpa bootstrapping getting issue below.

java: cannot find symbol
  symbol:   variable ENTITY_MANAGER
  location: class org.springframework.orm.jpa.EntityManagerHolder

**Comment by kwoyke** [comment] 2022-03-10 12:54
Hi @ameya ,
Can you please explain in details how to reproduce the issue?
I just checked the module on my end locally and everything works as expected.
Also our pipelines do not raise any failures.

**Comment by ameya** [comment] 2022-03-10 13:04
Hi @kwoyke thank you for your reply,  created a public version of code I am working with here.
https://stackoverflow.com/questions/71277431/resolving-error-in-bootstrapping-jpa-programmatically-in-java

**Comment by kwoyke** [comment] 2022-03-10 13:15
OK @ameya, so the issue is with your custom code. We'd like to keep the GitHub issues only for the problems with our code.
But of course, posting on StackOverflow is a great idea and I'm sure the community will help you solve the case :)

**Comment by ameya** [comment] 2022-03-10 13:30
This is a replication of your code, I have tried to replicate the issue faced on my code

**Comment by ameya** [comment] 2022-03-10 14:20
@kwoyke request to reopen until you have tried replicating this issue running the application in a standalone without the parent dependency.

**Comment by kwoyke** [comment] 2022-03-10 15:03
![image](https://user-images.githubusercontent.com/10830473/157689738-6cb2cc47-3515-4fff-98d3-d85f3d20efb6.png)

As I already mentioned, I double checked our code on my side. As you can see it works fine.
The only extra thing I did is running a mysql docker image and crated the sample users table and data.

**Comment by kwoyke** [comment] 2022-03-10 15:04
@ameya What JDK version do you use?

**Comment by ameya** [comment] 2022-03-10 15:44
JDK version
openjdk version "17.0.2" 2022-01-18 LTS
Local MySQL 8.0.23

**Comment by kwoyke** [comment] 2022-03-10 17:09
Most probably this is the issue @ameya - our codebase is JDK8 based. Please try with JDK8.

**Comment by ameya** [comment] 2022-03-11 02:59
Still working with Java 11 the compiler has a target 1.8. Also, check intillij has backward compatibility checked.
Deleted the project, pulled, deleted local repo. No is

sue with compilation this time and not seeing the above issue. But getting "javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify"

Attaching error.log and error.png

[error.log](https://github.com/eugenp/tutorials/files/8228645/error.log)
![error](https://user-images.githubusercontent.com/96557/157793738-9b85b25b-4e85-4945-9f6d-f6da85c3b7be.png)

**Comment by kwoyke** [comment] 2022-03-11 08:06
@ameya , as I already mentioned please use **JDK8** and try again.
See also this https://stackoverflow.com/questions/53131321/spring-boot-jdbc-javax-net-ssl-sslexception-closing-inbound-before-receiving-p

**Comment by ameya** [comment] 2022-03-11 11:22
@kwoyke selected JDK 8
![image](https://user-images.githubusercontent.com/96557/157857807-720dd5ee-92f3-4672-8bf4-bdc90cca2d4f.png)

Getting the following error now.
![image](https://user-images.githubusercontent.com/96557/157857711-9fa4f37f-e21e-417a-b29b-c1440759a819.png)

**Comment by kwoyke** [comment] 2022-03-11 11:36
Great, so the application work as expected @ameya.
User  is null because you don't have a user record with id 1 in your db.
Closing this one.

**Closed by kwoyke** 2022-03-11 11:36 UTC
Labels: waiting-for-feedback

**Comment by ameya** [comment] 2022-03-11 12:03
@kwoyke 
One small change is needed in the code.
Please change user id to data type int else we have to specify a default value for the field id. 
For MySQL datatype equivalent of long [MEDIUMTEXT](https://dev.mysql.com/doc/refman/8.0/en/other-vendor-data-types.html). If MEDIUMTEXT and we run the application we get the following error while trying to insert new records.

![image](https://user-images.githubusercontent.com/96557/157863464-ec5389e7-2dcc-406d-a6b7-cc1b2d4396af.png)


A simple fix is to convert the id to int and make it AI (Auto Increment)
