### ISSUE TITLE
The yarn 

### ISSUE THREAD

**Issue by sasconsul** [eugenp/tutorials#13646] opened 2023-03-15 04:04 UTC
When reading the article on jhipster I found that the line
"yarn global add generator-jhipster" does not work. It seems that yarn has changed.

**Comment by ulisseslima** [comment] 2023-03-18 01:31
Hey, @sasconsul.

We'll look into this.

Article: https://www.baeldung.com/jhipster

**Comment by ehsansasanian** [comment] 2023-04-19 22:27
Hey @sasconsul 
I checked it with the latest stable version of yarn (1.22.19) and just installed "generator-jhipster@7.9.3". Could you share what the error is?

**Comment by sasconsul** [comment] 2023-04-20 18:31
I install yarn again.  When I tried it with the instructions in the article, https://www.baeldung.com/jhipster#creating-a-project ,
 I get:
```
 | mkdir baeldung-app && cd baeldung-app

 | yo jhipster
Error jhipster

Package subpath './lib/util/namespace' is not defined by "exports" in /Users/sasconsul/node_modules/yeoman-environment/package.json
(node:77817) [DEP0164] DeprecationWarning: Implicit coercion to integer for exit code is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
```
I not tried the suggestion, I don't understand the syntax suggested.

**Comment by dbadu** [comment] 2023-04-26 09:43
Hi @sasconsul, I tried a couple of node versions **(20.0.0, 19.6.0, 18.16.0, 17.9.1, 16.20.0)** for JHipster version `v7.9.3`. The command `yo jhipster` ran without error for node@v.16.20.0.

If you don't want to change your node version, you can use JHipster version `v7.0.0`, which seems stable for latest node versions.

**Comment by sasconsul** [comment] 2023-04-26 18:08
I have tried with the latest TLS version of node.  At this point I think the problem is with the node installation -- not the tutorials.  There maybe something wrong in the node environment.

Attached is a log of the test.

[jhipter_bug_1.txt](https://github.com/eugenp/tutorials/files/11336034/jhipter_bug_1.txt)

**Comment by dbadu** [comment] 2023-04-28 08:01
@sasconsul , did you try the above suggestion I mentioned? 

Try: 
` yarn global add generator-jhipster@7.0.0 `

or 
` down grade the node version to node@v.16.20.0`

**Comment by dbadu** [comment] 2023-05-08 04:30
The above suggested version of JHipster along with the node js has been tested and the issue is not replicable for the specified versions. Hence closing the ticket.

**Closed by dbadu** 2023-05-08 04:30 UTC
Labels: triaged, on-jira
