### ISSUE TITLE
I can't clone the project...

### ISSUE THREAD

**Issue by canliture** [eugenp/tutorials#8467] opened 2020-01-03 03:23 UTC
The project is go large and I cloned the project so times.
How can I solve the problem...

**Comment by kwoyke** [comment] 2020-01-22 21:13
Hi @canliture,
Can you please provide more details? Are you facing some issues when actually cloning the project from GitHub or importing it to the IDE?

**Comment by kwoyke** [comment] 2020-01-26 09:02
@canliture I'm closing this issue as it's not clear what the real problem is and therefore we can't reproduce it.

**Closed by kwoyke** 2020-01-26 09:02 UTC
Labels: in progress
